apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zlmvqzvgm-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zlmvqzvgm-dotnet-basic-gitops